cmake_minimum_required(VERSION 3.20)
get_filename_component(repo_root "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)

set(retained_features
    ENABLE_AWS_S3 ENABLE_AZURE_BLOB_STORAGE ENABLE_KAFKA ENABLE_MYSQL ENABLE_LIBPQXX
    ENABLE_GRPC ENABLE_ARROW_FLIGHT ENABLE_PARQUET ENABLE_PROTOBUF ENABLE_AVRO
    ENABLE_EMBEDDED_COMPILER ENABLE_SSL REGISTER_URL_FUNCTION REGISTER_URL_TABLE_ENGINE
    REGISTER_URL_CLUSTER_FUNCTION REGISTER_DICTIONARY_SOURCE_HTTP REGISTER_DICTIONARY_SOURCE_CLICKHOUSE
    REGISTER_OBJECT_STORAGE_FUNCTION REGISTER_OBJECT_STORAGE_TABLE_ENGINE REGISTER_DATALAKE_FUNCTION
    REGISTER_KEEPER_MAP_TABLE_ENGINE REGISTER_TIMESERIES_FUNCTION REGISTER_TIMESERIES_TABLE_ENGINE)
foreach(feature IN LISTS retained_features)
    set(${feature} ON)
endforeach()

set(ENABLE_AIVEN_HARDENING OFF)
include("${repo_root}/cmake/aiven_hardening.cmake")
if (NOT ENABLE_CATBOOST OR NOT ENABLE_POSTGRESQL_SERVER OR NOT ENABLE_SQL_SECURITY_NONE)
    message(FATAL_ERROR "Upstream defaults changed")
endif()

set(ENABLE_CATBOOST OFF CACHE BOOL "Test explicit option" FORCE)
include("${repo_root}/cmake/aiven_hardening.cmake")
if (ENABLE_CATBOOST)
    message(FATAL_ERROR "Explicit feature option was ignored")
endif()

set(ENABLE_WASMTIME ON CACHE BOOL "Test existing cache" FORCE)
set(ENABLE_AIVEN_HARDENING ON)
include("${repo_root}/cmake/aiven_hardening.cmake")
foreach(feature IN ITEMS
    ENABLE_CATBOOST ENABLE_SQL_PROCESS_CONTROL ENABLE_SQL_SYNC_FILE_CACHE
    ENABLE_CLIENT_HTTP_HEADER ENABLE_POSTGRESQL_SERVER ENABLE_HTTP_AUTHENTICATION
    ENABLE_SQL_IMPERSONATION ENABLE_SQL_SECURITY_NONE ENABLE_KAFKA_MOCKS
    ENABLE_INPUT_FORMAT_ERROR_FILES ENABLE_WEB_OBJECT_STORAGE ENABLE_ACME
    ENABLE_CRASH_REPORTS ENABLE_REMOTE_SYSLOG ENABLE_GRAPHITE ENABLE_AMBIENT_AWS_CREDENTIALS
    ENABLE_AZURE_IDENTITY ENABLE_GCP_OAUTH ENABLE_ZONE_AUTODETECTION ENABLE_WEAK_PASSWORD_METHODS
    ENABLE_WASMEDGE ENABLE_WASMTIME ENABLE_SSH ENABLE_LDAP ENABLE_LIBURING
    ENABLE_CLICKHOUSE_EXTRA_TOOLS ENABLE_CLIENT_AI ENABLE_CHDIG ENABLE_SKIM
    REGISTER_FILE_FUNCTION REGISTER_BACKUP_RESTORE REGISTER_CUSTOM_DISK REGISTER_EXECUTABLE_UDF)
    if (${feature})
        message(FATAL_ERROR "Hardening left ${feature} enabled")
    endif()
endforeach()
foreach(feature IN LISTS retained_features)
    if (NOT ${feature})
        message(FATAL_ERROR "Hardening disabled required capability ${feature}")
    endif()
endforeach()
get_property(cached_wasmtime CACHE ENABLE_WASMTIME PROPERTY VALUE)
if (NOT cached_wasmtime)
    message(FATAL_ERROR "Hardening modified the caller's cached options")
endif()
message(STATUS "Aiven profile defaults, exclusions and retained capabilities passed")