if (TARGET ch_contrib::rocksdb)
    set(USE_ROCKSDB 1)
endif()
if (TARGET ch_contrib::arrow_flight)
    set(USE_ARROWFLIGHT 1)
endif()
if (TARGET ch_contrib::bzip2)
    set(USE_BZIP2 1)
endif()
if (TARGET ch_contrib::minizip)
    set(USE_MINIZIP 1)
endif()
if (TARGET ch_contrib::snappy)
    set(USE_SNAPPY 1)
endif()
if (TARGET ch_contrib::brotli)
    set(USE_BROTLI 1)
endif()
if (TARGET ch_contrib::hivemetastore)
    set(USE_HIVE 1)
endif()
if (TARGET ch_contrib::rdkafka)
    set(USE_RDKAFKA 1)
endif()
if (TARGET ch_rust::skim)
    set(USE_SKIM 1)
endif()
if (TARGET ch_rust::prql)
    set(USE_PRQL 1)
endif()
if (TARGET ch_rust::polyglot)
    set(USE_POLYGLOT 1)
endif()
if (TARGET OpenSSL::SSL)
    set(USE_SSL 1)
endif()
if (TARGET ch_contrib::jwt-cpp)
    set(USE_JWT_CPP 1)
endif()
if (TARGET ch_contrib::ldap)
    set(USE_LDAP 1)
endif()
if (TARGET ch_contrib::grpc)
    set(USE_GRPC 1)
endif()
if (TARGET ch_contrib::hdfs)
    set(USE_HDFS 1)
endif()
if (TARGET ch_contrib::nuraft)
    set(USE_NURAFT 1)
endif()
if (TARGET ch_contrib::icu)
    set(USE_ICU 1)
endif()
if (TARGET ch_contrib::simdjson)
    set(USE_SIMDJSON 1)
endif()
if (TARGET ch_contrib::rapidjson)
    set(USE_RAPIDJSON 1)
endif()
if (TARGET ch_contrib::azure_sdk)
    set(USE_AZURE_BLOB_STORAGE 1)
endif()
if (TARGET ch_contrib::amqp_cpp)
    set(USE_AMQPCPP 1)
endif()
if (TARGET ch_contrib::nats_io)
    set(USE_NATSIO 1)
endif()
if (TARGET ch_contrib::cassandra)
    set(USE_CASSANDRA 1)
endif()
if (TARGET ch_contrib::base64)
    set(USE_BASE64 1)
endif()
if (TARGET ch_contrib::yaml_cpp)
    set(USE_YAML_CPP 1)
endif()
if (OS_LINUX)
    set(USE_FILELOG 1)
endif()
if (TARGET ch_contrib::sqlite)
    set(USE_SQLITE 1)
endif()
if (TARGET ch_contrib::libpqxx)
    set(USE_LIBPQXX 1)
endif()
if (TARGET ch_contrib::krb5)
    set(USE_KRB5 1)
endif()
if (TARGET ch_contrib::datasketches)
    set(USE_DATASKETCHES 1)
endif()
if (TARGET ch_contrib::aws_s3)
    set(USE_AWS_S3 1)
endif()
if (TARGET ch_contrib::google_cloud_cpp)
    set(USE_GOOGLE_CLOUD 1)
endif()
if (ENABLE_GOOGLE_CLOUD_CPP_KMS)
    set(USE_GOOGLE_CLOUD_KMS 1)
endif()
if (TARGET ch_contrib::mariadbclient) # ch::mysqlxx
    set(USE_MYSQL 1)
endif()
if (ENABLE_NLP)
    set(USE_NLP 1)
endif()
if (TARGET ch_contrib::ulid)
    set(USE_ULID 1)
endif()
if (TARGET ch_contrib::llvm)
    set(USE_EMBEDDED_COMPILER ${ENABLE_EMBEDDED_COMPILER})
    set(USE_DWARF_PARSER ${ENABLE_DWARF_PARSER})
    set(USE_BLAKE3 ${ENABLE_LIBRARIES})
endif()
if (TARGET ch_contrib::replxx)
    set(USE_REPLXX 1)
endif()
if (TARGET ch_contrib::cpuid)
    set(USE_CPUID 1)
endif()
if (TARGET ch_contrib::jemalloc)
    set(USE_JEMALLOC 1)
endif()
if (TARGET ch_contrib::h3)
    set(USE_H3 1)
endif()
if (TARGET ch_contrib::s2)
    set(USE_S2_GEOMETRY 1)
endif()
if (TARGET ch_contrib::fastops)
    set(USE_FASTOPS 1)
endif()
if (TARGET ch_contrib::sqids)
    set(USE_SQIDS 1)
endif()
if (TARGET ch_contrib::bech32)
    set(USE_BECH32 1)
endif()
if (TARGET ch_contrib::idna)
    set(USE_IDNA 1)
endif()
if (TARGET ch_contrib::vectorscan)
    set(USE_VECTORSCAN 1)
endif()
if (TARGET ch_contrib::avrocpp)
    set(USE_AVRO 1)
endif()
if (TARGET ch_contrib::parquet)
    set(USE_PARQUET 1)
    set(USE_ARROW 1)
    set(USE_ORC 1)
endif()
if (TARGET ch_contrib::liburing)
    set(USE_LIBURING 1)
endif ()
if (TARGET ch_contrib::protobuf)
    set(USE_PROTOBUF 1)
endif()
if (TARGET ch_contrib::msgpack)
    set(USE_MSGPACK 1)
endif()
if (TARGET ch_contrib::capnp)
    set(USE_CAPNP 1)
endif()
if (TARGET ch_contrib::bcrypt)
    set(USE_BCRYPT 1)
endif()
if (TARGET ch_contrib::simsimd)
    set(USE_SIMSIMD 1)
endif()
if (TARGET ch_contrib::usearch)
    set(USE_USEARCH 1)
endif()
if (TARGET ch_contrib::fastpfor)
    set(USE_FASTPFOR 1)
endif()
if (TARGET ch_contrib::ssh)
    set(USE_SSH 1)
endif()
if (TARGET ch_contrib::libfiu)
    set(USE_LIBFIU 1)
endif()
if (TARGET ch_contrib::libarchive)
    set(USE_LIBARCHIVE 1)
endif()
if (TARGET ch_contrib::pocketfft)
    set(USE_POCKETFFT 1)
endif()
if (TARGET ch_contrib::prometheus_protobufs)
    set(USE_PROMETHEUS_PROTOBUFS 1)
endif()
if (TARGET ch_contrib::antlr4_grammars)
    set(USE_ANTLR4_GRAMMARS 1)
endif()
if (TARGET ch_contrib::mongocxx)
    set(USE_MONGODB 1)
endif()
if (TARGET ch_contrib::numactl)
    set(USE_NUMACTL 1)
endif()
if (TARGET ch_rust::delta_kernel_rs)
    set(USE_DELTA_KERNEL_RS 1)
endif()
if (TARGET ch_rust::chdig)
    set(USE_CHDIG 1)
endif()
if (ENABLE_FUZZING)
    set (USE_FUZZING_MODE 1)
endif()
if (ENABLE_BUZZHOUSE)
    set(USE_BUZZHOUSE 1)
endif()
if (ENABLE_CLIENT_AI)
    set(USE_CLIENT_AI 1)
endif()
if (TARGET ch_contrib::sha3iuf)
    set(USE_SHA3IUF 1)
endif()
if (TARGET ch_contrib::simdcomp)
    set(USE_SIMDCOMP 1)
endif()
if (TARGET ch_contrib::libcotp)
    set(USE_LIBCOTP 1)
endif()
if (TARGET ch_contrib::wasmedge)
    set(USE_WASMEDGE 1)
endif()
if (TARGET ch_rust::wasmtime)
    set(USE_WASMTIME 1)
endif()

set (USE_YTSAURUS 1)

# Compile-time toggles for individual dictionary sources (Aiven). Default ON to
# preserve upstream behavior; a command-line -DREGISTER_<NAME>=0/1 already in the
# cache wins, so production builds driven by explicit -D flags are unaffected.
# Using option() (not set(... 1)) is what makes the cache value win over this default.
option(REGISTER_DICTIONARY_LAYOUT_SSD "Register ssd_cache dictionary layout" ON)
option(REGISTER_DICTIONARY_SOURCE_CASSANDRA "Register Cassandra dictionary source" ON)
option(REGISTER_DICTIONARY_SOURCE_CLICKHOUSE "Register ClickHouse dictionary source" ON)
option(REGISTER_DICTIONARY_SOURCE_EXECUTABLE "Register Executable dictionary source" ON)
option(REGISTER_DICTIONARY_SOURCE_EXECUTABLEPOOL "Register ExecutablePool dictionary source" ON)
option(REGISTER_DICTIONARY_SOURCE_FILE "Register File dictionary source" ON)
option(REGISTER_DICTIONARY_SOURCE_HTTP "Register HTTP dictionary source" ON)
option(REGISTER_DICTIONARY_SOURCE_JDBC "Register JDBC dictionary source" ON)
option(REGISTER_DICTIONARY_SOURCE_LIBRARY "Register Library dictionary source" ON)
option(REGISTER_DICTIONARY_SOURCE_MONGODB "Register MongoDB dictionary source" ON)
option(REGISTER_DICTIONARY_SOURCE_MYSQL "Register MySQL dictionary source" ON)
option(REGISTER_DICTIONARY_SOURCE_POSTGRESQL "Register PostgreSQL dictionary source" ON)
option(REGISTER_DICTIONARY_SOURCE_REDIS "Register Redis dictionary source" ON)
option(REGISTER_DICTIONARY_SOURCE_XDBC "Register XDBC dictionary source" ON)
option(REGISTER_DICTIONARY_SOURCE_YAMLREGEXPTREE "Register YAMLRegExpTree dictionary source" ON)
option(REGISTER_DICTIONARY_SOURCE_YTSAURUS "Register YTsaurus dictionary source" ON)

# Compile-time toggles for individual table engines and table functions (Aiven).
# Default ON to preserve upstream behavior; a command-line -DREGISTER_<NAME>=0/1
# already in the cache wins, so production builds driven by explicit -D flags are
# unaffected. Using option() (not set(... 1)) is what makes the cache value win
# over this default. Sibling of the dictionary-source block above (patch 045).
option(REGISTER_AZURE_BLOB_QUEUE_TABLE_ENGINE "Register AzureQueue table engine" ON)
option(REGISTER_AZURE_BLOB_TABLE_ENGINE "Register Azure table engine" ON)
option(REGISTER_EXECUTABLE_TABLE_ENGINE "Register Executable table engine" ON)
option(REGISTER_EXTERNAL_DISTRIBUTED_TABLE_ENGINE "Register ExternalDistributed table engine" ON)
option(REGISTER_FILE_TABLE_ENGINE "Register File table engine" ON)
option(REGISTER_FILELOG_TABLE_ENGINE "Register FileLog table engine" ON)
option(REGISTER_ICEBERG_TABLE_ENGINE "Register Iceberg table engine" ON)
option(REGISTER_KEEPER_MAP_TABLE_ENGINE "Register KeeperMap table engine" ON)
option(REGISTER_LOG_TABLE_ENGINE "Register Log and StripeLog table engines" ON)
option(REGISTER_MONGODB_TABLE_ENGINE "Register MongoDB table engine" ON)
option(REGISTER_MYSQL_TABLE_ENGINE "Register MySQL table engine" ON)
option(REGISTER_NATS_TABLE_ENGINE "Register NATS table engine" ON)
option(REGISTER_ODBC_TABLE_ENGINE "Register ODBC and JDBC table engines" ON)
option(REGISTER_REDIS_TABLE_ENGINE "Register Redis table engine" ON)
option(REGISTER_S3_QUEUE_TABLE_ENGINE "Register S3Queue table engine" ON)
option(REGISTER_S3_TABLE_ENGINE "Register S3 table engine" ON)
option(REGISTER_URL_TABLE_ENGINE "Register URL table engine" ON)
option(REGISTER_AZURE_BLOB_FUNCTION "Register azureBlobStorage table function" ON)
option(REGISTER_EXECUTABLE_FUNCTION "Register executable table function" ON)
option(REGISTER_FILE_FUNCTION "Register file table function" ON)
option(REGISTER_HDFS_FUNCTION "Register hdfs table function" ON)
option(REGISTER_HIVE_FUNCTION "Register hive table function" ON)
option(REGISTER_MONGODB_FUNCTION "Register mongodb table function" ON)
option(REGISTER_ODBC_FUNCTION "Register odbc and jdbc table functions" ON)
option(REGISTER_REDIS_FUNCTION "Register redis table function" ON)
option(REGISTER_REMOTE_FUNCTION "Register remote table function" ON)
option(REGISTER_S3_FUNCTION "Register s3 table function" ON)
option(REGISTER_URL_CLUSTER_FUNCTION "Register urlCluster table function" ON)
option(REGISTER_URL_FUNCTION "Register url table function" ON)
option(REGISTER_TIMESERIES_TABLE_ENGINE "Register TimeSeries table engine" ON)
option(REGISTER_OBJECT_STORAGE_TABLE_ENGINE "Register generic ObjectStorage table engine" ON)
option(REGISTER_TIMESERIES_FUNCTION "Register timeSeries table function" ON)
option(REGISTER_OBJECT_STORAGE_FUNCTION "Register object-storage table functions (s3/azureBlobStorage/hdfs/...)" ON)
option(REGISTER_DATALAKE_FUNCTION "Register data-lake table functions (iceberg/deltaLake/hudi)" ON)
option(REGISTER_YTSAURUS_TABLE_ENGINE "Register YTsaurus table engine" ON)
option(REGISTER_YTSAURUS_FUNCTION "Register ytsaurus table function" ON)
option(REGISTER_ARROWFLIGHT_TABLE_ENGINE "Register ArrowFlight table engine" ON)
option(REGISTER_ARROWFLIGHT_FUNCTION "Register arrowFlight table function" ON)

# Compile-time toggle for the WebAssembly UDF subsystem (Aiven). Net-new in 26.3 - not
# part of the REGISTER_* engine/function port family. Gates `CREATE FUNCTION ... LANGUAGE
# WASM` and the `system.webassembly_modules` table at the single Context::initWasmModuleManager
# choke point. Default ON to preserve upstream behavior; orthogonal to USE_WASMTIME/USE_WASMEDGE
# (which backend is compiled) and to the experimental server setting
# `allow_experimental_webassembly_udf` (runtime enable, default off). Using option() (not
# set(... 1)) makes a command-line -DREGISTER_WEBASSEMBLY_UDF=0/1 win over this default.
option(REGISTER_WEBASSEMBLY_UDF "Register the WebAssembly UDF subsystem (CREATE FUNCTION ... LANGUAGE WASM)" ON)

option(REGISTER_EXECUTABLE_UDF "Register XML-configured executable user defined functions" ON)

# Compile-time toggle for BACKUP/RESTORE (Aiven). Gates `BackupsWorker::start`, the single funnel
# both kinds pass through, so the query parses and then fails with SUPPORT_IS_DISABLED rather than a
# syntax error. Upstream only restricts destinations at runtime via the
# `backups.allowed_path`/`allowed_disk` config, which is not set by default. Default ON to preserve
# upstream behavior; using option() (not set(... 1)) makes a command-line
# -DREGISTER_BACKUP_RESTORE=0/1 win over this default.
option(REGISTER_BACKUP_RESTORE "Register the BACKUP and RESTORE queries" ON)

# Compile-time toggle for inline custom disk definitions (Aiven). Gates the `disk(...)` function in
# `CREATE/ATTACH ... SETTINGS disk = disk(type=local, path=...)`, which lets ordinary DDL point a
# disk at an arbitrary filesystem location and bypass `user_files_path`. Upstream's only restriction
# is the `custom_local_disks_base_directory` config key, which is not enforced on ATTACH. Default ON
# to preserve upstream behavior; using option() (not set(... 1)) makes a command-line
# -DREGISTER_CUSTOM_DISK=0/1 win over this default.
option(REGISTER_CUSTOM_DISK "Register inline custom disk definitions (disk(...) in SETTINGS)" ON)

set(SOURCE_DIR ${PROJECT_SOURCE_DIR})
