option(ENABLE_AIVEN_HARDENING "Exclude unsupported Aiven server capabilities; preserve managed integrations and operator client" OFF)

option(ENABLE_CATBOOST "Enable CatBoost evaluation and model administration" ON)
option(ENABLE_SQL_PROCESS_CONTROL "Enable SQL shutdown, kill and suspend commands" ON)
option(ENABLE_SQL_SYNC_FILE_CACHE "Enable the SQL system-wide filesystem sync command" ON)
option(ENABLE_CLIENT_HTTP_HEADER "Enable SQL inspection of client HTTP headers" ON)
option(ENABLE_POSTGRESQL_SERVER "Enable inbound PostgreSQL wire protocol" ON)
option(ENABLE_HTTP_AUTHENTICATION "Enable external HTTP authentication" ON)
option(ENABLE_SQL_IMPERSONATION "Enable EXECUTE AS identity switching" ON)
option(ENABLE_SQL_SECURITY_NONE "Enable views without an execution security identity" ON)
option(ENABLE_KAFKA_MOCKS "Enable embedded librdkafka mock brokers" ON)
option(ENABLE_INPUT_FORMAT_ERROR_FILES "Enable file logging of rejected input rows" ON)
option(ENABLE_WEB_OBJECT_STORAGE "Enable Web object-storage disks" ON)
option(ENABLE_ACME "Enable built-in ACME certificate management" ON)
option(ENABLE_CRASH_REPORTS "Enable outbound crash reports" ON)
option(ENABLE_REMOTE_SYSLOG "Enable remote syslog transport" ON)
option(ENABLE_GRAPHITE "Enable outbound Graphite metrics" ON)
option(ENABLE_AMBIENT_AWS_CREDENTIALS "Enable implicit AWS credential providers" ON)
option(ENABLE_AZURE_IDENTITY "Enable Azure managed and workload identity providers" ON)
option(ENABLE_GCP_OAUTH "Enable GCP OAuth refresh-token authentication" ON)
option(ENABLE_ZONE_AUTODETECTION "Enable cloud metadata availability-zone discovery" ON)
option(ENABLE_WEAK_PASSWORD_METHODS "Enable passwordless and plaintext-stored password authentication" ON)
option(ENABLE_CLICKHOUSE_EXTRA_TOOLS "Enable local, disk administration, su and git-import modes" ON)

if (ENABLE_AIVEN_HARDENING)
    foreach(feature IN ITEMS
        ENABLE_CATBOOST ENABLE_SQL_PROCESS_CONTROL ENABLE_SQL_SYNC_FILE_CACHE
        ENABLE_CLIENT_HTTP_HEADER ENABLE_POSTGRESQL_SERVER ENABLE_HTTP_AUTHENTICATION
        ENABLE_SQL_IMPERSONATION ENABLE_SQL_SECURITY_NONE ENABLE_KAFKA_MOCKS
        ENABLE_INPUT_FORMAT_ERROR_FILES ENABLE_WEB_OBJECT_STORAGE ENABLE_ACME
        ENABLE_CRASH_REPORTS ENABLE_REMOTE_SYSLOG ENABLE_GRAPHITE
        ENABLE_AMBIENT_AWS_CREDENTIALS ENABLE_AZURE_IDENTITY ENABLE_GCP_OAUTH
        ENABLE_ZONE_AUTODETECTION ENABLE_WEAK_PASSWORD_METHODS
        ENABLE_CLICKHOUSE_EXTRA_TOOLS ENABLE_CLIENT_AI ENABLE_CHDIG ENABLE_SKIM
        ENABLE_WASMEDGE ENABLE_WASMTIME ENABLE_SSH ENABLE_LDAP ENABLE_LIBURING
        ENABLE_SQLITE ENABLE_ROCKSDB ENABLE_CASSANDRA ENABLE_AMQPCPP ENABLE_NATS
        ENABLE_HDFS ENABLE_HIVE
        REGISTER_WEBASSEMBLY_UDF REGISTER_EXECUTABLE_UDF REGISTER_BACKUP_RESTORE
        REGISTER_CUSTOM_DISK REGISTER_EXECUTABLE_TABLE_ENGINE REGISTER_EXECUTABLE_FUNCTION
        REGISTER_DICTIONARY_SOURCE_EXECUTABLE REGISTER_DICTIONARY_SOURCE_EXECUTABLEPOOL
        REGISTER_DICTIONARY_SOURCE_LIBRARY REGISTER_FILE_TABLE_ENGINE REGISTER_FILE_FUNCTION
        REGISTER_DICTIONARY_SOURCE_FILE REGISTER_FILELOG_TABLE_ENGINE
        REGISTER_MONGODB_FUNCTION REGISTER_MONGODB_TABLE_ENGINE REGISTER_DICTIONARY_SOURCE_MONGODB
        REGISTER_REDIS_FUNCTION REGISTER_REDIS_TABLE_ENGINE REGISTER_DICTIONARY_SOURCE_REDIS
        REGISTER_DICTIONARY_SOURCE_CASSANDRA REGISTER_ODBC_FUNCTION REGISTER_ODBC_TABLE_ENGINE
        REGISTER_DICTIONARY_SOURCE_XDBC REGISTER_DICTIONARY_SOURCE_JDBC
        REGISTER_NATS_TABLE_ENGINE REGISTER_HDFS_FUNCTION REGISTER_HIVE_FUNCTION
        REGISTER_ARROWFLIGHT_FUNCTION REGISTER_ARROWFLIGHT_TABLE_ENGINE
        REGISTER_YTSAURUS_FUNCTION REGISTER_YTSAURUS_TABLE_ENGINE REGISTER_DICTIONARY_SOURCE_YTSAURUS
        REGISTER_REMOTE_FUNCTION REGISTER_DICTIONARY_SOURCE_YAMLREGEXPTREE REGISTER_DICTIONARY_LAYOUT_SSD)
        set(${feature} OFF)
    endforeach()
endif()